export {};

type Supplier = { id:string; name:string; region:string; categories:string[]; capabilities:string[]; integration:string; sourceUrl:string; evidence:{reviewSource:string;reviewSummary:string;rating?:number;reviewCount?:number} };
const suppliers: Supplier[] = [
  {id:"vfulfill",name:"vFulfill",region:"India",categories:["General","Home","Beauty","Gadgets","Fashion"],capabilities:["Product research","Sourcing","COD","Fulfillment","Shopify"],integration:"SHOPIFY",sourceUrl:"https://apps.shopify.com/vfulfill-cod-dropshipping/reviews",evidence:{reviewSource:"Shopify App Store",reviewSummary:"4.7/5 from 11 reviews",rating:4.7,reviewCount:11}},
  {id:"qikink",name:"Qikink",region:"India",categories:["Print-on-demand","Fashion","Accessories"],capabilities:["Zero inventory","Printing","Branding","COD","Fulfillment"],integration:"API",sourceUrl:"https://qikink.com/dropshipping-india/",evidence:{reviewSource:"Official operating metrics",reviewSummary:"25,000+ sellers and 7M+ orders shipped claimed by Qikink"}},
  {id:"wholesalebox",name:"WholesaleBox",region:"India",categories:["Fashion","Women","Wholesale"],capabilities:["Dropshipping","Single-order fulfillment","Product feed","API subject to approval"],integration:"FEED",sourceUrl:"https://www.wholesalebox.in/dropshipper",evidence:{reviewSource:"Official dropshipper program",reviewSummary:"Dropshipping available; feed/API access is subject to store, sales and traffic criteria"}},
  {id:"seasonsway",name:"Seasonsway",region:"India",categories:["Fashion","Women","Kids","Men"],capabilities:["5,000+ references","Inventory","Dropshipping","API","Auto inventory updates"],integration:"API",sourceUrl:"https://www.seasonsway.com/india/dropshipping-india.php",evidence:{reviewSource:"Official dropshipping documentation",reviewSummary:"Documents KYC onboarding, direct delivery, API integration and automated inventory updates"}},
];
function esc(v:unknown){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));}
function render(){ if(location.pathname!=="/radar"&&location.pathname!=="/")return; const main=document.querySelector("main"); if(!main)return; let el=document.getElementById("akre-supplier-registry"); if(!el){el=document.createElement("section");el.id="akre-supplier-registry";main.appendChild(el);} el.innerHTML=`<div class="akre-discovery-head"><div><div class="akre-eyebrow">SUPPLIER INTELLIGENCE / INDIA</div><h2>Verified Supplier Network</h2><p>AKRE uses supplier evidence to validate availability and economics after trend discovery. Reviews and supplier claims are evidence, not guarantees of profitability.</p></div></div><div class="akre-provider-grid">${suppliers.map(s=>`<article><b>${esc(s.name)}</b><small>${esc(s.integration)} · ${esc(s.region)}</small><strong>${s.evidence.rating?`${s.evidence.rating}/5 · ${s.evidence.reviewCount} reviews`:"Evidence captured"}</strong><p>${esc(s.evidence.reviewSummary)}</p><a href="${esc(s.sourceUrl)}" target="_blank" rel="noreferrer">View source</a></article>`).join("")}</div><div class="akre-evidence-grid"><div class="akre-evidence-block"><div class="akre-block-title"><span>Supplier capabilities</span><em>${suppliers.length}</em></div>${suppliers.map(s=>`<div class="akre-product-row"><div><b>${esc(s.name)}</b><small>${esc(s.categories.join(" · "))}</small></div><span>${esc(s.capabilities.join(" · "))}</span><strong>${esc(s.integration)}</strong></div>`).join("")}</div><div class="akre-evidence-block"><div class="akre-block-title"><span>AKRE rule</span><em>LIVE</em></div><div class="akre-empty">Trend → classify as product → match supplier → verify price/stock/shipping → calculate margin → test. Supplier discovery never becomes purchase proof automatically.</div></div></div>`; }
setTimeout(render,400); window.addEventListener("popstate",()=>setTimeout(render,100)); new MutationObserver(()=>{if(!document.getElementById("akre-supplier-registry"))render();}).observe(document.body,{childList:true,subtree:true});
