export {};

type Supplier = { id:string; name:string; region:string; categories:string[]; capabilities:string[]; integration:string; sourceUrl:string; evidence:{reviewSource:string;reviewSummary:string;rating?:number;reviewCount?:number} };
type Row = Record<string, any>;
const suppliers: Supplier[] = [
  {id:"vfulfill",name:"vFulfill",region:"India",categories:["General","Home","Beauty","Gadgets","Fashion"],capabilities:["Product research","Sourcing","COD","Fulfillment","Shopify"],integration:"SHOPIFY",sourceUrl:"https://apps.shopify.com/vfulfill-cod-dropshipping/reviews",evidence:{reviewSource:"Shopify App Store",reviewSummary:"4.7/5 from 11 reviews",rating:4.7,reviewCount:11}},
  {id:"qikink",name:"Qikink",region:"India",categories:["Print-on-demand","Fashion","Accessories"],capabilities:["Zero inventory","Printing","Branding","COD","Fulfillment"],integration:"API",sourceUrl:"https://qikink.com/dropshipping-india/",evidence:{reviewSource:"Official operating metrics",reviewSummary:"25,000+ sellers and 7M+ orders shipped claimed by Qikink"}},
  {id:"wholesalebox",name:"WholesaleBox",region:"India",categories:["Fashion","Women","Wholesale"],capabilities:["Dropshipping","Single-order fulfillment","Product feed","API subject to approval"],integration:"FEED",sourceUrl:"https://www.wholesalebox.in/dropshipper",evidence:{reviewSource:"Official dropshipper program",reviewSummary:"Dropshipping available; feed/API access is subject to store, sales and traffic criteria"}},
  {id:"seasonsway",name:"Seasonsway",region:"India",categories:["Fashion","Women","Kids","Men"],capabilities:["5,000+ references","Inventory","Dropshipping","API","Auto inventory updates"],integration:"API",sourceUrl:"https://www.seasonsway.com/india/dropshipping-india.php",evidence:{reviewSource:"Official dropshipping documentation",reviewSummary:"Documents KYC onboarding, direct delivery, API integration and automated inventory updates"}},
];

function esc(v:unknown){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));}
async function json(path:string, init?:RequestInit){const r=await fetch(path,{credentials:"same-origin",...init});const text=await r.text();let body:any=null;try{body=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(body?.error||body?.detail||`Request failed (${r.status})`);return body;}

async function render(){
  if(location.pathname!=="/radar"&&location.pathname!=="/")return;
  const main=document.querySelector("main"); if(!main)return;
  let el=document.getElementById("akre-supplier-registry"); if(!el){el=document.createElement("section");el.id="akre-supplier-registry";main.appendChild(el);}
  let state: {data?:{products?:Row[];observations?:Row[]}}={};
  try{state=await json("/api/state");}catch{}
  const products=state.data?.products??[];
  const observations=state.data?.observations??[];
  const candidates=products.filter(p=>observations.some(o=>o.productName===p.name&&o.payload?.productClassification!=="NON_PRODUCT"));
  el.innerHTML=`<div class="akre-discovery-head"><div><div class="akre-eyebrow">COMMERCE DISCOVERY / INDIA</div><h2>Trend → Supplier Match</h2><p>AKRE now separates discovered attention/search signals from actual supplier evidence. A trend becomes sellable only after product intent, supplier, stock, shipping and margin checks.</p></div></div><div class="akre-provider-grid">${suppliers.map(s=>`<article><b>${esc(s.name)}</b><small>${esc(s.integration)} · ${esc(s.region)}</small><strong>${s.evidence.rating?`${s.evidence.rating}/5 · ${s.evidence.reviewCount} reviews`:"Evidence captured"}</strong><p>${esc(s.evidence.reviewSummary)}</p><a href="${esc(s.sourceUrl)}" target="_blank" rel="noreferrer">View source</a></article>`).join("")}</div><div class="akre-evidence-block"><div class="akre-block-title"><span>Discovered candidates</span><em>${candidates.length}</em></div>${candidates.length?candidates.slice(0,12).map(p=>{const o=observations.find(x=>x.productName===p.name);const c=o?.payload?.productClassification??"AMBIGUOUS";return `<div class="akre-product-row"><div><b>${esc(p.name)}</b><small>${esc(p.category)} · ${esc(c)}</small></div><button data-match="${esc(p.name)}">Find suppliers</button></div>`}).join(""): `<div class="akre-empty">No classified candidates yet. Run Google Trends discovery first.</div>`}</div><div class="akre-evidence-grid"><div class="akre-evidence-block" id="akre-supplier-results"><div class="akre-block-title"><span>Supplier matches</span><em>WAITING</em></div><div class="akre-empty">Select a candidate to match it against researched supplier capabilities and, when configured, the live CJ catalog.</div></div><div class="akre-evidence-block"><div class="akre-block-title"><span>Execution gate</span><em>ENFORCED</em></div><div class="akre-empty">Trend → classify → supplier match → real cost/stock/shipping → contribution margin → test → Shopify DRAFT. No purchase evidence is inferred from search.</div></div></div>`;
  el.querySelectorAll<HTMLButtonElement>("[data-match]").forEach(btn=>btn.addEventListener("click",async()=>{
    const query=btn.dataset.match||"";const results=el!.querySelector<HTMLElement>("#akre-supplier-results");if(!results)return;btn.disabled=true;btn.textContent="Matching…";results.innerHTML=`<div class="akre-block-title"><span>Supplier matches</span><em>SEARCHING</em></div><div class="akre-empty">Matching ${esc(query)} against researched supplier capabilities and CJ catalog.</div>`;
    try{
      const local=await json("/api/suppliers/catalogs/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})});
      let cj:any={configured:false};try{cj=await json("/api/suppliers/cj/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({keyword:query,countryCode:"IN",pageNum:1,pageSize:10})});}catch{}
      const localRows=(local.suppliers??[]).map((s:any)=>`<div class="akre-product-row"><div><b>${esc(s.name)}</b><small>${esc(s.status)} · ${esc(s.integration)} · ${esc(s.region)}</small></div><span>${esc((s.capabilities??[]).join(" · "))}</span><strong>${s.evidence?.rating?`${s.evidence.rating}/5`:"RESEARCHED"}</strong></div>`).join("");
      const cjRows=(cj.products??cj.data??[]).slice?.(0,5)?.map((p:any)=>`<div class="akre-product-row"><div><b>${esc(p.nameEn??p.name??p.sku??"CJ product")}</b><small>CJ · ${esc(p.sku??"")}</small></div><span>${esc(p.nowPrice??p.sellPrice??"Price unavailable")} USD</span><strong>${esc(p.warehouseInventoryNum??p.totalVerifiedInventory??"Stock unknown")}</strong></div>`).join("")??"";
      results.innerHTML=`<div class="akre-block-title"><span>Supplier matches for ${esc(query)}</span><em>${cj.configured===false?"CJ NOT CONFIGURED":"LIVE"}</em></div>${localRows||`<div class="akre-empty">No researched supplier catalog match for this exact query.</div>`}${cjRows?`<div class="akre-block-title"><span>Live CJ catalog</span><em>REAL API</em></div>${cjRows}`:`<div class="akre-empty">CJ live catalog is not configured or returned no match. Researched suppliers remain evidence-only until an account/feed/API is connected.</div>`}`;
    }catch(e){results.innerHTML=`<div class="akre-empty">${esc(e instanceof Error?e.message:"Supplier matching failed")}</div>`;}finally{btn.disabled=false;btn.textContent="Find suppliers";}
  }));
}
setTimeout(()=>void render(),400);
window.addEventListener("popstate",()=>setTimeout(()=>void render(),100));
new MutationObserver(()=>{if(!document.getElementById("akre-supplier-registry"))void render();}).observe(document.body,{childList:true,subtree:true});
